import Sidebar from '@/components/custom/sidebar/sidebar'
import { Inter } from 'next/font/google'
import '../assets/globals.scss'
import styles from './layout.module.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps { children: React.ReactNode }

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.page}`}>
        <Sidebar />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
